# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pomek.pl" # the base hostname & protocol for your site

socials:
  facebook: pomekPL
  twitter: pomekPL
  github: pomek
  twitch: pomekPL

# Build settings
markdown: kramdown

exclude:
  - "node_modules"
  - "bower_components"
  - "package.json"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"

gems: [jekyll-paginate]

jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

paginate: 3
paginate_path: ":num"
