# Site settings
title: blog.pomek.pl
email: pomek@pomek.pl
baseurl: ""
url: "https://blog.pomek.pl"

socials:
  facebook: pomekPL
  twitter: pomekPL
  github: pomek
  twitch: pomekPL

markdown: kramdown
permalink: /:year/:month/:day/:title.html

gems: [jekyll-paginate]
paginate: 5
paginate_path: ":num"

exclude:
  - "node_modules"
  - "bower_components"
  - "package.json"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"

jekyll-press:
  exclude: '*.xml'
  js_options: {}
  css_options: {}
  html_options: {}
