# Site settings
title: blog.pomek.pl
email: pomek@pomek.pl
baseurl: ""
url: "https://blog.pomek.pl"

socials:
  facebook: pomekPL
  twitter: pomekPL
  github: pomek
  twitch: pomekPL

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

gems: [jekyll-paginate]
paginate: 5
paginate_path: ":num"

exclude:
  - "node_modules"
  - "bower_components"
  - "package.json"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "js/.gitignore"
  - "readme.md"
  - "Gruntfile.js"
