# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pomek.pl" # the base hostname & protocol for your site
twitter_username: pomekPL
github_username:  pomek

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"

gems: [jekyll-paginate]

paginate: 2
paginate_path: ":num"
